### ISSUE TITLE
Option to delete attached evidence, co-applicants etc

### ISSUE THREAD

**Issue by arkie-boy** [nasullah/RDMDT#5]
You can add them, but you can't delete

**Comment by nasullah** [comment]
You can delete attached evidence from the show application page by clicking attached evidence link.

Nasullah

**Comment by arkie-boy** [comment]
Thanks.  We'll need to ensure this is in the user documentation we're going to have to write. 

We should add a 'delete evidence' button to the main form for usability in some future version though

Steve
