### ISSUE TITLE
Should you be able to assign more than one reviewer to an application?

### ISSUE THREAD

**Issue by arkie-boy** [nasullah/RDMDT#8]
It occurs to me that the administrator should be able to assign more than one reviewer to the application for online application review.

Each user should then be able to write a review about the current state of the application, adding subsequent reviews until the application is approved or ultimately refused.  Each review should be classified as either approved/rejected/more evidence required

Steve

**Comment by arkie-boy** [comment]
<img width="915" alt="screen shot 2016-10-12 at 10 43 29" src="https://cloud.githubusercontent.com/assets/5691883/19305448/d5eac0b6-9068-11e6-8aac-84daa9d09e65.png">

**Comment by nasullah** [comment]
That is great, but should we implement it now or wait for Jude to comment?

Nasullah

**Comment by arkie-boy** [comment]
Wait!!

:-)

**Comment by arkie-boy** [comment]
However, Jude did mention she couldn’t see how a reviewer can do the review, and the review fields are only available to the administrator.  They should be available to the reviewer too, and if possible they should not have the option to edit the rest of the application.

How long might this take?

Steve

On 12 Oct 2016, at 10:52, nasullah <notifications@github.com<mailto:notifications@github.com>> wrote:

That is great, but should we implement it now or wait for Jude to comment?

Nasullah

**Comment by arkie-boy** [comment]
Also the UML is a sketch. I don't know what the classes and attributes actually are ...

**Comment by nasullah** [comment]
I just finished the word document, I should be able to do the reviewer function in a couple of hours.

Nasullah

**Comment by Jude-RDPM** [comment]
Yes - this would be helpful, especially if they could be sequential.  JK (Chair of GM-MDT) reviews all non-Clinical Genetics applications for final sign off.  This function would allow him to do this even if the application had already been reviewed by Ed/other.  Alternatively, a facility for him to comment on 'review submitted' applications would also work and might be less untidy.  
We rarely ask the advice of more than one reviewer in situations other than this.

**Comment by nasullah** [comment]
Not needed
